/* ============================================
   DATA LAYER — Dein Start in Deutschland
   Central data management for Journey & Services
   ============================================ */

const SITE = {
  name: 'Dein Start in Deutschland',
  tagline: 'Die wichtigsten Schritte – einfach erklärt und Schritt für Schritt.',
  description: 'Du bist neu in Deutschland? Entdecke die wichtigsten Themen für deinen Start und finde schnell die passenden Services und Informationen.',
  url: '',
  lang: 'de',
};

const JOURNEY_PHASES = [
  {
    id: 'ankommen',
    number: '01',
    icon: '✈',
    title: 'Ankommen',
    subtitle: 'Dein erster Schritt',
    description: 'Die ersten wichtigen Dinge direkt nach deiner Ankunft in Deutschland.',
    colorVar: 'ankommen',
    items: [
      { title: 'Unterkunft', slug: 'unterkunft', available: false },
      { title: 'SIM-Karte & Internet', slug: 'sim-karte-internet', available: false },
      { title: 'Erste Orientierung', slug: 'erste-orientierung', available: false },
      { title: 'Krankenversicherung', slug: 'krankenversicherung-ankommen', available: false },
      { title: 'Wichtige Dokumente', slug: 'wichtige-dokumente-ankommen', available: false },
      { title: 'Notrufnummern & Erste Hilfe', slug: 'notrufnummern', available: false },
    ],
  },
  {
    id: 'wohnen',
    number: '02',
    icon: '🏠',
    title: 'Wohnen & Anmeldung',
    subtitle: 'Dein Zuhause finden',
    description: 'Wohnungssuche, Mietvertrag und die wichtige Anmeldung beim Bürgeramt.',
    colorVar: 'wohnen',
    items: [
      { title: 'Wohnung finden', slug: 'wohnung-finden', available: false },
      { title: 'Mietvertrag verstehen', slug: 'mietvertrag-verstehen', available: false },
      { title: 'Wohnungsgeberbestätigung', slug: 'wohnungsgeberbestaetigung', available: false },
      { title: 'Anmeldung beim Bürgeramt', slug: 'anmeldung-buergeramt', available: false },
      { title: 'Meldebescheinigung', slug: 'meldebescheinigung', available: false },
      { title: 'Gas, Strom & Wasser', slug: 'gas-strom-wasser', available: false },
      { title: 'Internet & Router', slug: 'internet-router', available: false },
      { title: 'GEZ / Rundfunkbeitrag', slug: 'gez-rundfunkbeitrag', available: false },
    ],
  },
  {
    id: 'aufenthalt',
    number: '03',
    icon: '🪪',
    title: 'Aufenthalt & Dokumente',
    subtitle: 'Dein Aufenthaltsstatus',
    description: 'Aufenthaltstitel, Arbeitserlaubnis und alle wichtigen Dokumente.',
    colorVar: 'aufenthalt',
    items: [
      { title: 'Aufenthaltstitel', slug: 'aufenthaltstitel', available: false },
      { title: 'Visum', slug: 'visum', available: false },
      { title: 'Ausländerbehörde', slug: 'auslaenderbehoerde', available: false },
      { title: 'Arbeitserlaubnis', slug: 'arbeitserlaubnis', available: false },
      { title: 'Niederlassungserlaubnis', slug: 'niederlassungserlaubnis', available: false },
      { title: 'Steuer-ID', slug: 'steuer-id', available: false },
      { title: 'Wichtige Dokumente', slug: 'wichtige-dokumente', available: false },
    ],
  },
  {
    id: 'finanzen',
    number: '04',
    icon: '🏦',
    title: 'Finanzen',
    subtitle: 'Geld & Bank',
    description: 'Bankkonto eröffnen, Gehalt verstehen und finanziell durchstarten.',
    colorVar: 'finanzen',
    items: [
      { title: 'Bankkonto', slug: 'bankkonto', available: false },
      { title: 'Gehalt verstehen', slug: 'gehalt-verstehen', available: false },
      { title: 'Kindergeld', slug: 'kindergeld', available: false },
      { title: 'Steuern & Steuererklärung', slug: 'steuern', available: false },
      { title: 'Sozialleistungen & BAföG', slug: 'sozialleistungen', available: false },
      { title: 'Überweisungen', slug: 'ueberweisungen', available: false },
      { title: 'Laufende Kosten', slug: 'laufende-kosten', available: false },
    ],
  },
  {
    id: 'mobilitaet',
    number: '05',
    icon: '🚆',
    title: 'Mobilität',
    subtitle: 'Fortbewegen in Deutschland',
    description: 'ÖPNV, Führerschein, Deutschlandticket und alle Mobilitäts-Infos.',
    colorVar: 'mobilitaet',
    items: [
      { title: 'ÖPNV', slug: 'oepnv', available: false },
      { title: 'Deutschlandticket', slug: 'deutschlandticket', available: false },
      { title: 'Führerschein', slug: 'fuehrerschein', available: false },
      { title: 'Auto', slug: 'auto', available: false },
      { title: 'Fahrrad', slug: 'fahrrad', available: false },
    ],
  },
  {
    id: 'versicherungen',
    number: '06',
    icon: '🛡',
    title: 'Versicherungen',
    subtitle: 'Absicherung für dein Leben',
    description: 'Krankenversicherung, Haftpflicht und weitere wichtige Versicherungen.',
    colorVar: 'versicherungen',
    items: [
      { title: 'Krankenversicherung', slug: 'krankenversicherung', available: false },
      { title: 'Privathaftpflicht', slug: 'privathaftpflicht', available: false },
      { title: 'Hausratversicherung', slug: 'hausratversicherung', available: false },
      { title: 'Weitere Versicherungen', slug: 'weitere-versicherungen', available: false },
    ],
  },
  {
    id: 'integration',
    number: '07',
    icon: '🗣',
    title: 'Sprache & Integration',
    subtitle: 'Ankommen im Alltag',
    description: 'Deutsch lernen, Integrationskurse, Bildung, Beruf und Community.',
    colorVar: 'integration',
    items: [
      { title: 'Deutsch lernen', slug: 'deutsch-lernen', available: false },
      { title: 'Integrationskurs', slug: 'integrationskurs', available: false },
      { title: 'Beruf & Arbeit', slug: 'beruf-arbeit', available: false },
      { title: 'Anerkennung von Abschlüssen', slug: 'abschluesse-integration', available: false },
      { title: 'Schule & Kita', slug: 'schule-kita', available: false },
      { title: 'Kindergarten & Betreuung', slug: 'kindergarten', available: false },
      { title: 'Studium & Ausbildung', slug: 'studium-ausbildung', available: false },
      { title: 'Community', slug: 'community', available: false },
      { title: 'Freizeit & Vereine', slug: 'freizeit', available: false },
    ],
  },
  {
    id: 'alltag',
    number: '08',
    icon: '💻',
    title: 'Alltag & Digitale Services',
    subtitle: 'Dein digitaler Alltag',
    description: 'Online-Banking, Behördenportale, wichtige Apps und digitale Services.',
    colorVar: 'alltag',
    items: [
      { title: 'Online-Banking', slug: 'online-banking', available: false },
      { title: 'Behördenportale', slug: 'behoerdenportale', available: false },
      { title: 'Wichtige Apps', slug: 'wichtige-apps', available: false },
      { title: 'Internetanbieter', slug: 'internet-anbieter', available: false },
      { title: 'Rundfunkbeitrag', slug: 'rundfunkbeitrag', available: false },
      { title: 'Weitere Services', slug: 'weitere-services', available: false },
    ],
  },
];

const SERVICE_CATEGORIES = [
  {
    id: 'wohnen',
    icon: '🏠',
    title: 'Wohnen',
    description: 'Wohnung, Anmeldung & Relocation',
    colorVar: 'wohnen',
    journeyLink: 'wohnen',
    services: [
      { title: 'Wohnungssuche', slug: 'wohnungssuche', available: false, type: 'internal' },
      { title: 'Relocation-Unterstützung', slug: 'relocation', available: false, type: 'internal' },
      { title: 'Mietvertrag', slug: 'mietvertrag', available: false, type: 'internal' },
      { title: 'Anmeldung', slug: 'anmeldung', available: false, type: 'internal' },
      { title: 'Gas, Strom & Wasser', slug: 'gas-strom-wasser-service', available: false, type: 'internal' },
      { title: 'Internet & Rundfunkbeitrag', slug: 'internet-rundfunk', available: false, type: 'internal' },
      { title: 'Wohnungsbezogene Services', slug: 'wohnungs-services', available: false, type: 'internal' },
    ],
  },
  {
    id: 'behoerden',
    icon: '🪪',
    title: 'Behörden & Dokumente',
    description: 'Anmeldung, Aufenthalt, Übersetzungen',
    colorVar: 'aufenthalt',
    journeyLink: 'aufenthalt',
    services: [
      { title: 'Anmeldung', slug: 'anmeldung-behoerde', available: false, type: 'internal' },
      { title: 'Aufenthalt', slug: 'aufenthalt-service', available: false, type: 'internal' },
      { title: 'Ausländerbehörde', slug: 'auslaenderbehoerde-service', available: false, type: 'internal' },
      { title: 'Dokumente', slug: 'dokumente', available: false, type: 'internal' },
      { title: 'Übersetzungen', slug: 'uebersetzungen', available: false, type: 'internal' },
      { title: 'Behördliche Unterstützung', slug: 'behoerdsupport', available: false, type: 'internal' },
    ],
  },
  {
    id: 'mobilitaet',
    icon: '🚗',
    title: 'Mobilität',
    description: 'Führerschein, Auto & Deutschlandticket',
    colorVar: 'mobilitaet',
    journeyLink: 'mobilitaet',
    services: [
      { title: 'Führerschein', slug: 'fuehrerschein-service', available: false, type: 'internal' },
      { title: 'Auto', slug: 'auto-service', available: false, type: 'internal' },
      { title: 'Versicherung', slug: 'auto-versicherung', available: false, type: 'internal' },
      { title: 'Deutschlandticket', slug: 'deutschlandticket-service', available: false, type: 'internal' },
      { title: 'Fahrzeugbezogene Services', slug: 'fahrzeug-services', available: false, type: 'internal' },
    ],
  },
  {
    id: 'versicherungen',
    icon: '🛡',
    title: 'Versicherungen',
    description: 'Krankenversicherung, Haftpflicht & mehr',
    colorVar: 'versicherungen',
    journeyLink: 'versicherungen',
    services: [
      { title: 'Krankenversicherung', slug: 'krankenversicherung-service', available: false, type: 'internal' },
      { title: 'Privathaftpflicht', slug: 'privathaftpflicht-service', available: false, type: 'internal' },
      { title: 'Hausratversicherung', slug: 'hausratversicherung-service', available: false, type: 'internal' },
      { title: 'Weitere Versicherungen', slug: 'weitere-versicherungen-service', available: false, type: 'internal' },
    ],
  },
  {
    id: 'finanzen',
    icon: '🏦',
    title: 'Finanzen',
    description: 'Bankkonto, Geldtransfer & Steuern',
    colorVar: 'finanzen',
    journeyLink: 'finanzen',
    services: [
      { title: 'Bankkonto', slug: 'bankkonto-service', available: false, type: 'internal' },
      { title: 'Geldtransfer', slug: 'geldtransfer', available: false, type: 'internal' },
      { title: 'Kindergeld', slug: 'kindergeld-service', available: false, type: 'internal' },
      { title: 'Steuern', slug: 'steuern-service', available: false, type: 'internal' },
      { title: 'Sozialleistungen', slug: 'sozialleistungen-service', available: false, type: 'internal' },
      { title: 'Finanzielle Services', slug: 'finanz-services', available: false, type: 'internal' },
    ],
  },
  {
    id: 'integration',
    icon: '🗣',
    title: 'Sprache & Integration',
    description: 'Deutschkurse, Integrationskurse & Community',
    colorVar: 'integration',
    journeyLink: 'integration',
    services: [
      { title: 'Deutschkurse', slug: 'deutschkurse', available: false, type: 'internal' },
      { title: 'Integrationskurse', slug: 'integrationskurse', available: false, type: 'internal' },
      { title: 'Sprachpartner', slug: 'sprachpartner', available: false, type: 'internal' },
      { title: 'Schule & Kindergarten', slug: 'schule-kindergarten', available: false, type: 'internal' },
      { title: 'Community', slug: 'community-service', available: false, type: 'internal' },
      { title: 'Freizeit', slug: 'freizeit-service', available: false, type: 'internal' },
    ],
  },
  {
    id: 'karriere',
    icon: '💼',
    title: 'Arbeit & Karriere',
    description: 'Jobs, Bewerbungen & Anerkennung',
    colorVar: 'ankommen',
    journeyLink: null,
    services: [
      { title: 'Jobs finden', slug: 'jobs-finden', available: false, type: 'internal' },
      { title: 'Bewerbungen', slug: 'bewerbungen', available: false, type: 'internal' },
      { title: 'Lebenslauf', slug: 'lebenslauf', available: false, type: 'internal' },
      { title: 'Anerkennung von Abschlüssen', slug: 'abschluesse', available: false, type: 'internal' },
      { title: 'Karriereberatung', slug: 'karriereberatung', available: false, type: 'internal' },
    ],
  },
  {
    id: 'digital',
    icon: '💻',
    title: 'Digitale Services',
    description: 'Online-Banking, Apps & Internet',
    colorVar: 'alltag',
    journeyLink: 'alltag',
    services: [
      { title: 'Online-Banking', slug: 'online-banking-service', available: false, type: 'internal' },
      { title: 'Behördenportale', slug: 'behoerdenportale-service', available: false, type: 'internal' },
      { title: 'Apps', slug: 'apps-service', available: false, type: 'internal' },
      { title: 'Internet', slug: 'internet-service', available: false, type: 'internal' },
      { title: 'Digitale Dienstleistungen', slug: 'digitale-dienste', available: false, type: 'internal' },
    ],
  },
];

const NAV_LINKS = [
  { label: 'Startseite', href: 'index.html', id: 'home' },
  { label: 'Services', href: 'services.html', id: 'services' },
];

const FOOTER_LINKS = {
  navigation: [
    { label: 'Startseite', href: 'index.html' },
    { label: 'Services', href: 'services.html' },
  ],
  legal: [
    { label: 'Impressum', href: 'impressum.html', available: false },
    { label: 'Datenschutz', href: 'datenschutz.html', available: false },
  ],
  info: [
    { label: 'Über uns', href: 'ueber-uns.html', available: false },
    { label: 'Kontakt', href: 'kontakt.html', available: false },
  ],
};
